### ISSUE TITLE
mutation summary fails if facets has not been run

### ISSUE THREAD

**Issue by hxrts** [jrflab/modules#95]
annotdf doesn't have a default assignment of None.

```
Traceback (most recent call last):
  File "modules/scripts/mutation_summary_excel.py", line 280, in <module>
    main()
  File "modules/scripts/mutation_summary_excel.py", line 277, in main
    args.max_exac_af)
  File "modules/scripts/mutation_summary_excel.py", line 209, in write_mutation_summary
    facetsdf=facetsdf, annotdf=annotdf)
UnboundLocalError: local variable 'annotdf' referenced before assignment
modules/summary/mutationSummary.mk:43: recipe for target 'summary/mutation_summary.xlsx' failed
```

full log [here](/ifs/e63data/reis-filho/data/acc+mga/log/mutation_summary.2016-01-29.log)

**Comment by inodb** [comment]
Seems like this has been solved in the latest commit
